### ISSUE TITLE
History Tags

### ISSUE THREAD

**Issue by mndys** [mndys/capstone-project#16]
## Value Proposition (User Story)
As a **user**,
I would like to see my previous prompts **as tags**
because it makes them easier to **dinstinguish from each other**
## Description (Text, Scribble, Design)
*Wireframe before coding*
![Wireframe - History Tags](https://user-images.githubusercontent.com/28728929/111776326-29b1b380-88b2-11eb-97d3-974aa29662f3.png)

*Screenshot after coding*
![Screenshot - History Tags](https://user-images.githubusercontent.com/28728929/111713444-e9b9e480-884f-11eb-884d-91c95800f232.png)
## Acceptance Criteria
- [x] History is no longer converted to a comma-separated string
- [x] Each history entry lives in its own div, rendered with padding and background-color
### Bonus Feature
- [x] There is a loading animation for prompts while the wheel is spinning
## Tasks
- [x] Create LoadingCircles component
- [x] Animate circles
- [x] Implement LoadingCircles component
- [x] Adjust History component to deliver separate Entry components for each previous prompt in the history
## Story Points (Complexity)
S
