### ISSUE TITLE
Prompt Info

### ISSUE THREAD

**Issue by mndys** [mndys/capstone-project#17]
## Value Proposition
As a **user**,
I might need **more context** regarding my prompt
so I know how to **interpret** it
## Description
*Scribble*
![PromptInfo](https://user-images.githubusercontent.com/28728929/112049703-4408bd00-8b50-11eb-90ba-d2191d459a8f.png)
*Screenshot after coding*
![Bildschirmfoto am 2021-03-23 um 20 33 34](https://user-images.githubusercontent.com/28728929/112049841-70bcd480-8b50-11eb-8e31-fce0be579661.png)
## Acceptance Criteria
- [x]  Prompts can be clicked and display a modal with more information
- [x]  History items can be clicked and display a modal with more information
- [x]  Loading Circles cannot be clicked
- [x]  Initial prompt cannot be clicked
- [x]  Last prompt cannot be clicked
## Tasks
- [x]  Create feature branch
- [x]  Create PromptInfo component
- [x] Add Logic
- [x]  Style PromptInfo
- [x]  Adjust data json
- [x]  Write tests
- [x]  Add PromptInfo to Storybook
## Story Points
M
