### ISSUE TITLE
Prompt Helpers

### ISSUE THREAD

**Issue by mndys** [mndys/capstone-project#20]
## Value Statement
As a **receiver of the prompts "Page Number" or "Cover Color"**,
I get a r**andom number or color** in the prompt and in the prompt info modal
to **specify the given prompt**
## Description
_Scribble_
![getRandomColour-getRandomPageNumber](https://user-images.githubusercontent.com/28728929/112395604-05fdcb80-8cff-11eb-943f-76910bd21fd5.png)
_Screenshots after Coding_
![Color](https://user-images.githubusercontent.com/28728929/112396440-72c59580-8d00-11eb-9ca5-f1451577f0f8.png)
![Page](https://user-images.githubusercontent.com/28728929/112396394-5b86a800-8d00-11eb-87a1-e259aa39baa2.png)
![Color and Page](https://user-images.githubusercontent.com/28728929/112396451-75c08600-8d00-11eb-8ada-582f0205882a.png)
## Acceptance Criteria
- [x] Prompt "Cover Colour" shows a random color in Prompt and PromptInfo components
- [x] Prompt "Page Number" shows a random color in Prompt and PromptInfo components
- [x] Prompt Helpers stay stable on change of Prompt or clicks on History Elements change while their prompts are shown
## Tasks
- [x] Write helper functions
- [x] Implement states
- [x] Write PromptSpecifier component
- [x] Write logic for displaying the right Prompt Helper at the right time and place
## Story Points
L
