### ISSUE TITLE
Spinning Wheel

### ISSUE THREAD

**Issue by mndys** [mndys/capstone-project#3]
## Value Proposition (User Story)
As a **user**,
I would like to see a **spinning wheel** when I click the spinButton
so the process feels a little **realer and more fun**
## Description (Text, Scribble, Design)
![User Story 4](https://user-images.githubusercontent.com/28728929/110125510-ada07180-7dc3-11eb-8b3c-8e4a283525e7.png)
## Acceptance Criteria (Edge Cases)
- [ ] wheel starts spinning on button click
- [ ] wheel stops spinning after 3 secs
## Tasks
- [ ] Create feature branch
- [ ] Create SVG for Wheel
- [ ] Create SVG for Pointer
- [ ] Create Wheel component
- [ ] Render Wheel component
- [ ] Animate Wheel component
- [ ] Write test for animation
- [ ] Add onClick to Button
- [ ] Write Test for onClick
- [ ] Add missing styling
## Story Points (Complexity)
L
