### ISSUE TITLE
Get Prompt

### ISSUE THREAD

**Issue by mndys** [mndys/capstone-project#4]
## Value Proposition (User Story)
As a **user**,
I would like to get a **prompt** by clicking a button
which helps me **choose my next read**
## Description (Text, Scribble, Design)
![User Story 1(1)](https://user-images.githubusercontent.com/28728929/110127652-2c96a980-7dc6-11eb-86b1-6a499f037974.png)
## Acceptance Criteria (Edge Cases)
- [x] There is a Button
- [x] A new prompt is displayed when the button is clicked
## Tasks
- [x] Create feature branch
- [x] Create state hook for currentPrompt
- [x] Create Button component
- [x] Create Prompt component
- [x] Research Prompts (~20)
- [x] Create prompts array
- [x] Add onClick logic for Button
- [x] Write test for Button
- [x] Write test for ButtonClick
- [x] Write test for Prompt
- [x] Add missing styling
## Story Points (Complexity)
M
