### ISSUE TITLE
Prompt History

### ISSUE THREAD

**Issue by mndys** [mndys/capstone-project#5]
## Value Proposition (User Story)
As a **user**,
I would like to see a **history** of previous prompts
so that I can see what my prompts were **at a glance**
## Description (Text, Scribble, Design)
![User Story 2](https://user-images.githubusercontent.com/28728929/110129698-84361480-7dc8-11eb-9e17-f15722b1ec58.png)
## Acceptance Criteria (Edge Cases)
- [x] Previous prompts are added and displayed at the bottom of the screen after a new prompt is generated
- [x] There is a cap of all unique prompts in the history. After that, the spin button will be disabled and the currentPrompt will ask the user to reload the page
## Tasks
- [x] Create feature branch
- [x] Create state hook for history
- [x] Create History component
- [x] Write History test
- [x] Write History story
## Story Points (Complexity)
S
