### ISSUE TITLE
Reset History

### ISSUE THREAD

**Issue by mndys** [mndys/capstone-project#6]
## Value Proposition (User Story)
As a **user**,
I need to **reset my history**
because I want to **start over**
## Description (Text, Scribble, Design)
![User Story 3](https://user-images.githubusercontent.com/28728929/110136876-8308e580-7dd0-11eb-8448-fc97cf648bfe.png)
## Acceptance Criteria (Edge Cases)
- [x] history is cleared
- [x] history state hook is an empty array
## Tasks
- [x] Create instance of Button as reset button
- [x] Add logic to update history state hook
- [x] Add localStorage for history
- [x] Write test for History component
- [x] Write test for localStorage
## Story Points (Complexity)
M
